apiVersion: v1
data:
  args-1: '--character-set-server=utf8mb4'
  args-2: '--collation-server=utf8mb4_bin'
  args-3: '--explicit-defaults-for-timestamp=1'
  args-4: '--datadir=/var/lib/mysql/data'
kind: ConfigMap
metadata:
  name: mysql-args
