apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web
spec:
  host: xwiki-x.apps.openshift.sebastian-colomar.es
  to:
    kind: Service
    name: xwiki-web
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
